Display tax information when creating a subscription
blockprotocol/blockprotocol pull request #1050
Opened 2023-02-26 21:30 UTC by benwerner01

## 🌟 What is the purpose of this PR?

## 🔗 Related links

- [Asana task](link) _(internal)_

## 🚫 Blocked by

- [ ] ...

## 🔍 What does this change?

- ...

## 📜 Does this require a change to the docs?

- The docs for x need updating to explain that y

## ⚠️ Known issues

## 🐾 Next steps

## 🛡 What tests cover this?

-

## ❓ How to test this?

1.  Checkout the branch / view the deployment
1.  Try X
1.  Confirm that Y

## 📹 Demo

2023-02-27 03:24 UTC, luisbettencourt requested changes
Code looks good, but noticed that when upgrading a subscription tax information isn't shown (it displays a difference of $6 but in the payment history it displays $7.60 so I'm assuming it scales with the subscription tier.

2023-02-28 18:32 UTC, benwerner01 commented
> Code looks good, but noticed that when upgrading a subscription tax information isn't shown (it displays a difference of $6 but in the payment history it displays $7.20 so I'm assuming it scales with the subscription tier.

Thanks for catching, have addressed in https://github.com/blockprotocol/blockprotocol/pull/1050/commits/2a03ae0c83a58822367e979ef2668c818ca24b70. This required adding an additional route to the internal API, so to test this you'll need to checkout the `bw/get-tax-rate` branch on the internal API repo.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/42802102/221946773-7e331f68-5297-4345-ab52-0a85bd6a2b4a.png">

2023-02-28 18:58 UTC, luisbettencourt submitted a review, later dismissed

2023-02-28 22:19 UTC, luisbettencourt submitted a review, later dismissed

2023-03-01 13:50 UTC, merged