[SITE] Dashboard to create API Keys
blockprotocol/blockprotocol pull request #109
Opened 2022-01-19 11:50 UTC by akash-joshi

## What this Does

## How to test it

## Demo

2022-01-19 20:32 UTC, CiaranMn commented
I've hooked this up to the real API - see demo below.

@akash-joshi can you do the following tomorrow as a priority:
1. Sort the mobile styling out
2. Make the whole of dashboard cards clickable (not just the link)

Note that I've removed some hardcoding styles that were applied when we should be using values from the MUI theme. We shouldn't be specifying any font sizes, button styles, colours, etc, anywhere except the MUI theme.

We'll need to revisit this to clear up the other hardcoded values, and sort out some of the button styles in the theme which don't match the design system, but for now please just focus on (1) and (2) above.

https://user-images.githubusercontent.com/37743469/150208868-b423a922-405c-4f86-b02c-bcee4855c438.mp4

2022-01-20 07:32 UTC, akash-joshi commented
@CiaranMn commit https://github.com/blockprotocol/blockprotocol/pull/109/commits/659648f3a4058169533f7f34f5a7ba4d910a91b1 implement 1 & 2 from your previous comment.

1. Sort the mobile styling out

I believe the buttons were missing some margin on mobile, which I fixed.

![NptjzmiYZD](https://user-images.githubusercontent.com/22196279/150293302-1160b8c7-581f-4925-b7fa-0bf79541af34.png)


2. Make the whole of dashboard cards clickable (not just the link)

Have moved the links from the child element to the parent.

2022-01-20 07:58 UTC, CiaranMn requested changes
Thanks Akash - there are a few more quick things we can do to make mobile better and more closely aligned with the designs:

1. The "Dashboard" / "API Keys" tabs at the top disappears on mobile - it is present in the designs on mobile. This component also repeats between the dashboard and api-keys page - I'd extract this and re-use it.

2. Various boxes could do with less padding on smaller sizes, e.g. this one (please check others for padding in the designs vs here)
![Screenshot 2022-01-20 at 07 47 53](https://user-images.githubusercontent.com/37743469/150296647-0f39c981-009d-4a85-9dd2-9c0f5ed95536.png)

3. We should give the table cells sufficient width to avoid wrapping here
![Screenshot 2022-01-20 at 07 49 32](https://user-images.githubusercontent.com/37743469/150296737-18d77f41-0978-4ec0-9aff-6464b9e0fb5b.png)

4. Buttons should generally be full width on mobile
![Screenshot 2022-01-20 at 07 48 17](https://user-images.githubusercontent.com/37743469/150296877-a2e01f53-9346-4f57-a6d4-878eb8617795.png)

2022-01-20 09:29 UTC, akash-joshi commented
Have made the above changes.

![chrome_jIlEscrPEE](https://user-images.githubusercontent.com/22196279/150311268-559b2aaf-bc34-4db4-aa2d-532a0da61c26.gif)

The header won't wrap either now - [link](https://github.com/blockprotocol/blockprotocol/pull/109/commits/e00229f8ef10dc40c320a92ba5e810d7069e153e#diff-c37885c632d5f871b9c5d7630cae8c3e1ff2745668df75e498fabd927aa5f999R28)

2022-01-20 11:45 UTC, CiaranMn requested changes
Please extract the tabs into its own component - it's going to be much easier to add to it later rather than updating in two places.

2022-01-20 13:58 UTC, akash-joshi commented on site/src/components/pages/dashboard/TopNavigationTabs.tsx
> +            dashboardPages.find((dashboardPage) =>
This is a heuristic way to determine the current page, so it doesn't get affected by hashes or query parameters. This component in itself could eventually be created into a generic reusable component.

2022-01-20 14:00 UTC, CiaranMn approved these changes
Thanks Akash, let's get this in

2022-01-20 17:22 UTC, merged