Update copy regarding Mapbox Autofill free allowance
blockprotocol/blockprotocol pull request #1112
Opened 2023-03-03 13:42 UTC by benwerner01

## 🌟 What is the purpose of this PR?

This PR updates copy in the BP site to reflect the updated Mapbox Autofill free allowances:
- 10 sessions for free users
- 25 sessions for Hobby users
- 50 sessions for Pro users

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203623179643287/1204092897972678/f) _(internal)_

2023-03-03 14:23 UTC, nonparibus requested changes
@benwerner01 Missed one instance of address autofills for hobby users that I can see

<img width="457" alt="Capture 2023-03-03 at 14 22 43@2x" src="https://user-images.githubusercontent.com/6226576/222744796-c8a0d04f-3373-49a6-8653-5370b62af06f.png">

2023-03-03 14:42 UTC, benwerner01 commented
> @benwerner01 Missed one instance of address autofills for hobby users that I can see


Thanks for spotting, addressed in https://github.com/blockprotocol/blockprotocol/pull/1112/commits/5dd3d61e3a04cbe447bb1a9d0aec1d8d893e404e

2023-03-03 20:40 UTC, nonparibus approved these changes
Functionally this looks good to me. Hopefully @luisbettencourt or @CiaranMn can take a look at the code tonight or over the weekend and we can get this allowance bump accurately reflected on the live site.

2023-03-06 22:07 UTC, luisbettencourt approved these changes
Thank you @benwerner01

2023-03-07 10:57 UTC, merged