Add "GPT-3.5 Turbo" copy to the BP site
blockprotocol/blockprotocol pull request #1129
Opened 2023-03-07 11:54 UTC by benwerner01

## 🌟 What is the purpose of this PR?

This PR adds "GPT-3.5 Turbo" copy to the BP site, informing users of the price and free allowance of the "GPT-3.5 Turbo" OpenAI model.

## 🔗 Related links

- [Asana task](https://app.asana.com/0/1203623179643290/1204092897972686/f) _(internal)_

## 📹 Demo

<img width="688" alt="image" src="https://user-images.githubusercontent.com/42802102/223414909-bf77ec1e-7e16-4833-8903-0879ccc444b0.png">

<img width="444" alt="image" src="https://user-images.githubusercontent.com/42802102/223414899-015360c0-0cdb-4bae-93b0-4debd241cca9.png">

2023-03-07 13:01 UTC, nonparibus requested changes
Left Vercel comments requesting changes

2023-03-07 15:24 UTC, benwerner01 commented
> Left Vercel comments requesting changes

Thanks David, I think I've addressed all of them as part of https://github.com/blockprotocol/blockprotocol/pull/1129/commits/975f22727e6042f96da48448d94bcb787c04dfc0 and  https://github.com/blockprotocol/blockprotocol/pull/1129/commits/019270ecc2d85daf6fb699b2afaad9937d637a58.

2023-03-08 16:08 UTC, nonparibus approved these changes
You can ignore my additional Vercel comments asking for a squiggle. This is actually fine as-is. Functionally approved; code review should follow.

2023-03-09 10:56 UTC, CiaranMn approved these changes

2023-03-09 11:23 UTC, merged