Dw/updates
blockprotocol/blockprotocol pull request #1177
Opened 2023-03-15 12:52 UTC by nonparibus

## 🌟 What is the purpose of this PR?

## 🔗 Related links

- [Asana task](link) _(internal)_

## 🚫 Blocked by

- [ ] ...

## 🔍 What does this change?

- ...

## 📜 Does this require a change to the docs?

- The docs for x need updating to explain that y

## ⚠️ Known issues

## 🐾 Next steps

## 🛡 What tests cover this?

-

## ❓ How to test this?

1.  Checkout the branch / view the deployment
1.  Try X
1.  Confirm that Y

## 📹 Demo

2023-03-16 17:21 UTC, nonparibus commented on apps/site/src/_pages/docs/5_faq.mdx
> +- **through the Þ Hub:** in addition to blocks and types, endpoints (APIs) can also be made accessible via the Þ Hub. Currently available endpoints include _OpenAI_ and _Mapbox_. **All Block Protocol
```suggestion
- **through the Þ Hub:** in addition to blocks and types, endpoints (APIs) can also be made accessible via the Þ Hub. Currently available endpoints include _OpenAI_ and _Mapbox_. All Block Protocol users receive free credits for use with these services, and receive discounted access through Þ Hobby and Þ Pro subscriptions. Individual embedding applications can additionally override the Block Protocol API's handling of any available service, and choose to resolve these themselves, falling back to the Block Protocol's support for services or ignoring them entirely. Read more in the [Service module](https://blockprotocol.org/docs/spec/service-module) specification.
```

2023-03-16 21:42 UTC, CiaranMn approved these changes

2023-03-17 10:02 UTC, Alfred-Mountfield requested changes
Small typo, also linting is broken. Few offline threads to clear up too :)

2023-03-21 15:19 UTC, CiaranMn approved these changes

2023-03-21 16:51 UTC, merged