[BE] Allow users to upload avatars through S#
blockprotocol/blockprotocol pull request #174
Opened 2022-02-01 17:00 UTC by thehabbos007

This PR allows users to upload avatars to their profiles.
Images are uploaded to AWS S3 on a bucket specified by env vars.

Outstanding:
- Documenting new environment variables added
- Documenting new endpoint and shape of requests for it
- Consider not using multipart when only one image is uploaded

2022-02-02 10:13 UTC, thehabbos007 commented
@kachkaev because of a non-resolved issue (with a PR open) on https://github.com/aws/aws-sdk-js-v3/pull/ PR 2700 (not linked as to not create a backreference) I had to pin to an older version of the library which makes `yarn-deduplicate` complain.
I am not sure how to fix this. Do you have a good way to handle this issue [seen here](https://github.com/blockprotocol/blockprotocol/runs/5034795208?check_suite_focus=true)?

2022-02-03 10:44 UTC, CiaranMn requested changes
Thanks Ahmad - I tested this out and it worked with small image files, but not with a couple of bigger ones (example avatar attached). It never makes it to the callback on `form.parse`.

![avatar](https://user-images.githubusercontent.com/37743469/152327754-ddb0e7a9-7694-4875-b565-7c8e0373cb44.jpeg)

2022-02-03 10:44 UTC, CiaranMn commented on site/src/pages/api/uploadUserAvatar.api.ts
> +      throw new Error("No file given. Please upload a file.");
There's a `formatErrors` function that standardises how errors are returned - we should give them all status codes too (where anticipated / user error) so they don't come through as `500`:
```suggestion
      res.status(400).json(
        formatErrors({
          msg: "No file given. Please upload a file.",
          param: "image",
        }),
      );
```

2022-02-03 10:44 UTC, CiaranMn commented on site/src/lib/middleware/imageUploadMultipart.ts
> +      // we are only interested with the _first_ file, so other fields are ignored.
I would return an error somewhere to alert the user to bad input, either:
(a) return an error here if more than one file is provided, or
(b) return an array of files here and let each API route decide how many files it wants (and return an error if there are too many)

2022-02-03 10:44 UTC, CiaranMn commented on site/src/lib/middleware/imageUploadMultipart.ts
> +  if (contentType && contentType.indexOf("multipart/form-data") !== -1) {
```suggestion
  if (contentType?.includes("multipart/form-data")) {
```

2022-02-03 10:47 UTC, CiaranMn commented on site/src/lib/middleware/imageUploadMultipart.ts
> +      // we are only interested with the _first_ file, so other fields are ignored.
Not sure what `maxFiles` is doing on the formidable config as adding 2 files to the form doesn't trigger anything

2022-02-03 11:22 UTC, thehabbos007 commented
Hmm, this is quite interesting behavior from the formidable library. I would expect an `error` in case of files too big, but it's silent and doesn't emit any error at all. I'll investigate.

2022-02-03 14:19 UTC, thehabbos007 commented
Formidable has been switched out with busboy, and with that a change from Streams to Buffers. Busboy is in-memory first unlike Formidable. And switchign to buffers means any logic errors won't sink the request into a waiting loop like before.

The new error checks are more clear now, and everything is async instead of callback-based. File validation happens from the middleware now. I've also removed the hack around S3, as it's not needed when dealing with buffers. Everything should be simpler now :)

cc: @CiaranMn

2022-02-04 10:47 UTC, CiaranMn requested changes
Thanks Ahmad, this is working well for me now with various images.

One thing that we could improve is: at the moment, it's irrelevant what body property the user passes an image in via - as long as there's a single file, it will be attached to `body.upload`. 

This isn't a big deal for this endpoint at the moment, but if we ever change this route or add others which require more than a single field, it might lead to them getting mixed up.

We could alternatively return from `imageUploadMultipart` keyed by the user-supplied field name, and use those as the keys on the body.

2022-02-09 09:28 UTC, merged