Display example-graph data in Block Hub
blockprotocol/blockprotocol pull request #328
Opened 2022-06-08 14:46 UTC by teenoh

2022-06-13 17:59 UTC, CiaranMn requested changes
Thanks @teenoh, this works well – I have a suggestion on tab naming, and one on how we pass the props to MockBlockDock

2022-06-13 17:59 UTC, CiaranMn commented on site/src/components/pages/hub/block-data-tabs.tsx
> +      {showExampleGraphTab && <Tab label="Example Graph" />}
```suggestion
      {showExampleGraphTab && <Tab label="Mock Datastore" />}
```

2022-06-13 23:18 UTC, teenoh commented on site/src/pages/api/rewrites/sandboxed-block-demo.api.ts
> +  };
I didn't consider that. Thanks for catching

2022-06-14 06:36 UTC, CiaranMn approved these changes

2022-06-14 11:12 UTC, merged