Update Footer
blockprotocol/blockprotocol pull request #432
Opened 2022-07-12 21:05 UTC by teenoh

Minor update to the site's footer.

2022-07-12 21:08 UTC, kachkaev commented on site/src/components/footer.tsx
> -                <HASHLogoIcon />
This component is still defined in the codebase, but we no longer use it. I think we can delete it entirely on `main` and then restore from git history, if needed.

2022-07-12 21:10 UTC, kachkaev requested changes
See a comment with a minor suggestion 👀

2022-07-12 22:30 UTC, nonparibus approved these changes

2022-07-13 07:20 UTC, kachkaev approved these changes

2022-07-13 11:27 UTC, merged