Block verification badges
blockprotocol/blockprotocol pull request #970
Opened 2023-02-12 17:20 UTC by luisbettencourt

## 🌟 What is the purpose of this PR?

## 🔗 Related links

- [Asana task](link) _(internal)_

## 🚫 Blocked by

- [ ] ...

## 🔍 What does this change?

- ...

## 📜 Does this require a change to the docs?

- The docs for x need updating to explain that y

## ⚠️ Known issues

## 🐾 Next steps

## 🛡 What tests cover this?

-

## ❓ How to test this?

1.  Checkout the branch / view the deployment
1.  Try X
1.  Confirm that Y

## 📹 Demo

2023-02-13 12:39 UTC, nathggns commented
Reviewing

2023-02-13 12:42 UTC, nathggns approved these changes

2023-02-13 12:42 UTC, nathggns commented on apps/site/src/pages/[shortname]/blocks/[block-slug].page.tsx
> +                      background: "#FBF7FF",
We should look at naming this colour at some point as its being used more and more

2023-02-13 12:43 UTC, kachkaev approved these changes

2023-02-13 12:46 UTC, kachkaev requested changes
Hmm do we have a mechanism to get the `verified` field for blocks that are published from the API? `/hub` directory will be removed in https://github.com/blockprotocol/blockprotocol/pull/936.

2023-02-13 15:51 UTC, luisbettencourt commented on apps/site/src/pages/[shortname]/blocks/[block-slug].page.tsx
> +                      Verified
I agree. @nonparibus what do you think?

2023-02-13 15:53 UTC, luisbettencourt commented
> Hmm do we have a mechanism to get the `verified` field for blocks that are published from the API? `/hub` directory will be removed in #936.

I see. Are those jsons being moved, or outright removed? If they are getting removed where will that information come from?

2023-02-14 04:21 UTC, nonparibus commented on apps/site/src/pages/[shortname]/blocks/[block-slug].page.tsx
> +                      Verified
Agreed. Please ticketize for follow-up. No need to block on this.

2023-02-14 04:23 UTC, nonparibus commented
@luisbettencourt Blocks won't be able to self-declare they are verified. This is information that will be added to a database record per relevant Hub listing. cc @CiaranMn

2023-02-14 10:34 UTC, luisbettencourt commented
> @luisbettencourt Blocks won't be able to self-declare they are verified. This is information that will be added to a database record per relevant Hub listing. cc @CiaranMn

@CiaranMn, given this should I remove the code that handles looking for the `verified` field in the block's json, or do we not care that it stays?

2023-02-14 10:36 UTC, luisbettencourt commented on apps/site/src/pages/[shortname]/blocks/[block-slug].page.tsx
> +                      Verified
Created a [subtask ](https://app.asana.com/0/0/1203966325298247/f) to track this.

2023-02-14 10:47 UTC, luisbettencourt commented on apps/site/src/pages/[shortname]/blocks/[block-slug].page.tsx
> +                      Verified
@nonparibus, went ahead and added the tooltip in this PR, as it was a quick addition to make. Just let me know what the Tooltip should read as, right now it reads: `This block is verified`

2023-02-14 11:06 UTC, CiaranMn commented
> @CiaranMn, given this should I remove the code that handles looking for the `verified` field in the block's json, or do we not care that it stays?

I don't think it matters either way, they'll be gone in a few days anyway.

2023-02-17 15:22 UTC, CiaranMn approved these changes

2023-02-17 15:24 UTC, merged